import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shadcn-space/blocks/navbar-01/navbar";
import { Footer2 } from "@/components/footer2";
// import Footer from "@/components/shadcn-space/blocks/footer-01/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Tea dak code everything in layout krob page ng see vea rhot */}
        <Navbar></Navbar>
        {children}
        <Footer2></Footer2>
        
        </body>
    </html>
  );
}
